#!/bin/sh
cd "${0%/*}" || exit 1
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions 2>/dev/null || true
blockMesh > log.blockMesh 2>&1
cp -r 0 0.orig 2>/dev/null || true
setFields > log.setFields 2>&1
interFoam > log.interFoam 2>&1
echo done
